[[constraint]]
  branch = "devel"
  name = "github.com/getlantern/flashlight"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/fronted"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/golog"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/keyman"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/yaml"

[[override]]
  name = "github.com/templexxx/reedsolomon"
  version = "0.1.1"

[[override]]
  name = "github.com/lucas-clemente/quic-go"
  branch = "master"
  source = "https://github.com/getlantern/quic-go"

[[override]]
  name = "github.com/marten-seemann/qtls"
  branch = "qtls"
  source = "https://github.com/marten-seemann/qtls-deprecated"

[prune]
  go-tests = true
  unused-packages = true
