[[constraint]]
  branch = "master"
  name = "github.com/getlantern/errors"

[[constraint]]
  branch = "devel"
  name = "github.com/getlantern/flashlight"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/fronted"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/golog"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/keyman"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/yaml"

[[override]]
  name = "github.com/templexxx/reedsolomon"
  version = "0.1.1"

[prune]
  go-tests = true
  unused-packages = true
